# Generated by Django 3.2.12 on 2024-03-09 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
    ]
